# Generated by Django 4.2.25 on 2026-05-09 16:18

from django.db import migrations, models
import django.db.models.deletion


def set_default_listing_channel_flags(apps, schema_editor):
    SalesChannel = apps.get_model('crm', 'SalesChannel')
    channel_flags = {
        'Ozon': True,
        'Яндекс Маркет': True,
        'Avito': True,
        'Самовывоз': False,
        'Сарафанное радио': False,
    }
    for channel_name, is_listing_channel in channel_flags.items():
        SalesChannel.objects.filter(name=channel_name).update(is_listing_channel=is_listing_channel)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_warehouse_saleschannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crm/products/')),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.organization')),
            ],
            options={
                'ordering': ['name', 'sku', 'id'],
            },
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='is_listing_channel',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_default_listing_channel_flags, noop_reverse),
        migrations.CreateModel(
            name='ProductChannelOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='crm.saleschannel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_offers', to='crm.product')),
            ],
            options={
                'ordering': ['channel__name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productchanneloffer',
            constraint=models.UniqueConstraint(fields=('product', 'channel'), name='uniq_crm_product_channel_offer'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='uniq_crm_product_organization_sku'),
        ),
    ]
