# Generated by Django 4.2.25 on 2026-05-11 00:00

from django.db import migrations, models
import django.db.models.deletion


def migrate_purchase_counterparties_and_statuses(apps, schema_editor):
    Counterparty = apps.get_model('crm', 'Counterparty')
    Purchase = apps.get_model('crm', 'Purchase')
    StockLot = apps.get_model('crm', 'StockLot')
    StockMovement = apps.get_model('crm', 'StockMovement')

    for purchase in Purchase.objects.all().iterator():
        supplier_name = (purchase.supplier_name or '').strip()
        if supplier_name:
            counterparty, _ = Counterparty.objects.get_or_create(
                organization_id=purchase.organization_id,
                name=supplier_name,
                defaults={
                    'comment': '',
                    'is_active': True,
                },
            )
            purchase.counterparty_id = counterparty.id

        purchase.status = 'posted' if purchase.is_active else 'cancelled'
        purchase.save(update_fields=['counterparty', 'status'])

        if not purchase.is_active:
            StockMovement.objects.filter(related_purchase_item__purchase_id=purchase.id).delete()
            StockLot.objects.filter(purchase_item__purchase_id=purchase.id).delete()


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_purchase_purchaseitem_stocklot_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='crm.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='crm.counterparty'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведена'), ('cancelled', 'Отменена')], default='posted', max_length=16),
        ),
        migrations.RunPython(migrate_purchase_counterparties_and_statuses, noop_reverse),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_active',
        ),
    ]
