# Generated by Django 4.2.25 on 2026-05-11 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_counterparty_purchase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_methods', to='crm.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_order_number', models.CharField(blank=True, max_length=32, null=True)),
                ('external_order_number', models.CharField(blank=True, max_length=255)),
                ('order_date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=64)),
                ('customer_contact', models.CharField(blank=True, max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('awaiting_shipment', 'Ожидает отправки / самовывоз'), ('in_delivery', 'В доставке'), ('pickup_point', 'В ПВЗ'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('returned', 'Возврат')], default='new', max_length=32)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено'), ('partially_paid', 'Частично оплачено'), ('refunded', 'Возврат оплаты')], default='unpaid', max_length=32)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('marketplace', 'Маркетплейс'), ('other', 'Другое')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_created_orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.deliverymethod')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.organization')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.saleschannel')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='crm.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='crm.product')),
                ('source_price_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_with_price_source', to='crm.saleschannel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Активен'), ('released', 'Освобожден'), ('consumed', 'Списан')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='crm.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='crm.orderitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='crm.organization')),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='crm.stocklot')),
            ],
            options={
                'ordering': ['stock_lot__purchase_item__purchase__purchase_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('organization', 'internal_order_number'), name='uniq_crm_order_organization_internal_number'),
        ),
        migrations.AddConstraint(
            model_name='deliverymethod',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_crm_delivery_method_organization_code'),
        ),
    ]
