from django.urls import path

from .views import (
    counterparty_archive_view,
    counterparty_create_view,
    counterparty_edit_view,
    counterparty_restore_view,
    dashboard_view,
    delivery_method_archive_view,
    delivery_method_create_view,
    delivery_method_edit_view,
    delivery_method_restore_view,
    onboarding_view,
    order_cancel_view,
    order_create_view,
    order_detail_view,
    order_edit_view,
    orders_view,
    purchase_archive_view,
    purchase_create_view,
    purchase_detail_view,
    purchase_edit_view,
    purchase_template_download_view,
    purchases_view,
    product_archive_view,
    product_bulk_import_view,
    product_create_view,
    product_edit_view,
    product_template_download_view,
    products_view,
    sales_channel_archive_view,
    sales_channel_create_view,
    sales_channel_edit_view,
    sales_channel_restore_view,
    settings_view,
    warehouse_archive_view,
    warehouse_create_view,
    warehouse_edit_view,
    warehouse_restore_view,
)


app_name = 'crm'


urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('onboarding/', onboarding_view, name='onboarding'),
    path('orders/', orders_view, name='orders'),
    path('orders/create/', order_create_view, name='order_create'),
    path('orders/<int:order_id>/', order_detail_view, name='order_detail'),
    path('orders/<int:order_id>/edit/', order_edit_view, name='order_edit'),
    path('orders/<int:order_id>/cancel/', order_cancel_view, name='order_cancel'),
    path('purchases/', purchases_view, name='purchases'),
    path('purchases/create/', purchase_create_view, name='purchase_create'),
    path('purchases/template/', purchase_template_download_view, name='purchase_template_download'),
    path('purchases/<int:purchase_id>/', purchase_detail_view, name='purchase_detail'),
    path('purchases/<int:purchase_id>/edit/', purchase_edit_view, name='purchase_edit'),
    path('purchases/<int:purchase_id>/archive/', purchase_archive_view, name='purchase_archive'),
    path('products/', products_view, name='products'),
    path('products/import/', product_bulk_import_view, name='product_bulk_import'),
    path('products/template/', product_template_download_view, name='product_template_download'),
    path('products/create/', product_create_view, name='product_create'),
    path('products/<int:product_id>/edit/', product_edit_view, name='product_edit'),
    path('products/<int:product_id>/archive/', product_archive_view, name='product_archive'),
    path('settings/', settings_view, name='settings'),
    path('settings/channels/create/', sales_channel_create_view, name='sales_channel_create'),
    path('settings/channels/<int:channel_id>/edit/', sales_channel_edit_view, name='sales_channel_edit'),
    path('settings/channels/<int:channel_id>/archive/', sales_channel_archive_view, name='sales_channel_archive'),
    path('settings/channels/<int:channel_id>/restore/', sales_channel_restore_view, name='sales_channel_restore'),
    path('settings/warehouses/create/', warehouse_create_view, name='warehouse_create'),
    path('settings/warehouses/<int:warehouse_id>/edit/', warehouse_edit_view, name='warehouse_edit'),
    path('settings/warehouses/<int:warehouse_id>/archive/', warehouse_archive_view, name='warehouse_archive'),
    path('settings/warehouses/<int:warehouse_id>/restore/', warehouse_restore_view, name='warehouse_restore'),
    path('settings/delivery-methods/create/', delivery_method_create_view, name='delivery_method_create'),
    path('settings/delivery-methods/<int:delivery_method_id>/edit/', delivery_method_edit_view, name='delivery_method_edit'),
    path('settings/delivery-methods/<int:delivery_method_id>/archive/', delivery_method_archive_view, name='delivery_method_archive'),
    path('settings/delivery-methods/<int:delivery_method_id>/restore/', delivery_method_restore_view, name='delivery_method_restore'),
    path('settings/counterparties/create/', counterparty_create_view, name='counterparty_create'),
    path('settings/counterparties/<int:counterparty_id>/edit/', counterparty_edit_view, name='counterparty_edit'),
    path('settings/counterparties/<int:counterparty_id>/archive/', counterparty_archive_view, name='counterparty_archive'),
    path('settings/counterparties/<int:counterparty_id>/restore/', counterparty_restore_view, name='counterparty_restore'),
]
