# Generated by Django 4.2.25 on 2026-02-28 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('reimbursement', 'Возврат'), ('transfer_pair', 'Перевод между счетами'), ('exchange_pair', 'Обмен')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('archived', 'В архиве')], default='active', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_link_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Основная'), ('offset', 'Компенсация'), ('outgoing', 'Исходящая'), ('incoming', 'Входящая')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.transactionlinkgroup')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_items', to='core.transaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='transactionlinkitem',
            constraint=models.UniqueConstraint(fields=('group', 'transaction'), name='uniq_group_transaction_item'),
        ),
        migrations.AddConstraint(
            model_name='transactionlinkitem',
            constraint=models.UniqueConstraint(fields=('transaction',), name='uniq_transaction_link_item'),
        ),
    ]
